export type ErrorCode =
  | "AUTH_REQUIRED"
  | "AUTH_INVALID_CREDENTIALS"
  | "AUTH_EMAIL_NOT_VERIFIED"
  | "AUTH_SESSION_EXPIRED"
  | "SESSION_REQUIRED"
  | "CONSENT_REQUIRED"
  | "FILE_TOO_LARGE"
  | "FILE_UNSUPPORTED"
  | "FILE_CORRUPT"
  | "FILE_DUPLICATE"
  | "STORAGE_FAILED"
  | "AI_TIMEOUT"
  | "AI_INVALID_RESPONSE"
  | "AI_CONFIGURATION_REQUIRED"
  | "LOW_CONFIDENCE"
  | "RUN_BLOCKED"
  | "RUN_LIMIT_REACHED"
  | "EXPORT_FAILED"
  | "UNAUTHORIZED"
  | "NOT_FOUND"
  | "INVALID_REQUEST"
  | "SAFETY_VIOLATION"
  | "CONFIGURATION_ERROR"
  | "PARTIAL_DELETION"
  | "NETWORK_ERROR"
  | "PORTFOLIO_CREATE_FAILED"
  | "REVIEW_FAILED"
  | "CORRECTION_REQUIRED"
  | "DOCUMENT_NOT_FOUND"
  | "INSUFFICIENT_TEXT"
  | "CLASSIFICATION_FAILED"
  | "ORGANIZATION_REVIEW_REQUIRED"
  | "DUPLICATE_DOCUMENT"
  | "DATABASE_WRITE_FAILED"
  | "RELATIONSHIP_FAILED"
  | "MEDICINE_QUERY_REQUIRED"
  | "MEDICINE_NOT_FOUND"
  | "AMBIGUOUS_MEDICINE_MATCH"
  | "FORMULATION_NOT_CONFIRMED"
  | "SOURCE_UNAVAILABLE"
  | "SOURCE_TIMEOUT"
  | "SOURCE_RATE_LIMITED"
  | "SOURCE_INVALID_RESPONSE"
  | "LABEL_NOT_FOUND"
  | "LABEL_SECTION_UNAVAILABLE"
  | "PRESCRIPTION_ITEM_NOT_FOUND"
  | "CITATION_VALIDATION_FAILED"
  | "REPORT_NOT_FOUND"
  | "REPORT_ACCESS_DENIED"
  | "EXTRACTION_FAILED"
  | "MEASUREMENT_EXTRACTION_FAILED"
  | "INSUFFICIENT_TEXT"
  | "DATABASE_ERROR"
  | "CAMERA_NOT_SUPPORTED"
  | "CAMERA_PERMISSION_DENIED"
  | "CAMERA_DEVICE_NOT_FOUND"
  | "CAMERA_DEVICE_BUSY"
  | "CAMERA_INSECURE_CONTEXT"
  | "CAPTURE_FAILED"
  | "IMAGE_DECODE_FAILED"
  | "IMAGE_TOO_SMALL"
  | "IMAGE_TOO_LARGE"
  | "IMAGE_TOO_BLURRY"
  | "UNSUPPORTED_FILE_TYPE"
  | "FILE_SIGNATURE_MISMATCH"
  | "FILE_EMPTY"
  | "TOO_MANY_PAGES"
  | "DUPLICATE_DOCUMENT"
  | "UPLOAD_SESSION_FAILED"
  | "SIGNED_URL_EXPIRED"
  | "UPLOAD_FAILED"
  | "UPLOAD_CANCELLED"
  | "UPLOAD_VERIFICATION_FAILED"
  | "DOCUMENT_FINALIZATION_FAILED"
  | "INTERNAL_ERROR";

export function createError(code: ErrorCode, message: string) {
  return { code, message };
}

export function formatErrorResponse(
  error: { code: string; message: string },
  requestId: string
) {
  return {
    data: null,
    error: { code: error.code, message: error.message },
    requestId,
  };
}

export function generateRequestId(): string {
  return Math.random().toString(36).substring(2, 15);
}
