/**
 * Medicine safety — dosage boundaries, emergency detection, safety disclaimers.
 */

// ─── Safety Disclaimers ───────────────────────────────────────────────────

export const SAFETY_DISCLAIMERS = {
  /** Shown on every medicine page */
  GENERAL:
    "Healthfolio retrieves medicine information from supported authoritative sources. " +
    "Coverage depends on medicine, country, formulation, and source availability. " +
    "This information is not a substitute for professional medical advice.",

  /** Shown under "Your prescription" */
  PRESCRIPTION:
    "This is a transcription of your uploaded prescription. " +
    "Healthfolio has not verified whether this dose is appropriate for you. " +
    "Always confirm medication instructions with a licensed healthcare professional.",

  /** Shown under "Official label information" */
  LABEL:
    "This is general label information and is not a personalized dosage recommendation. " +
    "Do not change your medication without consulting a healthcare professional.",

  /** Shown when AI simplifies text */
  AI_EXPLANATION:
    "The following explanation was generated by AI based on official label content. " +
    "It is for informational purposes only and does not replace the official label text.",

  /** Shown when medicine cannot be verified */
  UNAVAILABLE:
    "We could not verify this medicine from the currently supported authoritative sources. " +
    "Check the spelling, search by active ingredient, or consult a licensed pharmacist.",

  /** Shown when age-specific info is missing */
  NO_AGE_INFO:
    "No verified age-specific information was found in the supported official label. " +
    "Consult a healthcare professional for age-specific guidance.",

  /** Shown for Indian medicines without verified ingredient */
  UNVERIFIED_INGREDIENT:
    "Active ingredient not verified for this brand. " +
    "Please check the package label or consult a pharmacist to confirm the active ingredient.",
} as const;

// ─── Emergency Detection ──────────────────────────────────────────────────

const EMERGENCY_KEYWORDS = [
  "overdose",
  "severe allergic reaction",
  "anaphylaxis",
  "breathing difficulty",
  "difficulty breathing",
  "loss of consciousness",
  "chest pain",
  "heart attack",
  "stroke",
  "seizure",
  "poisoning",
  "emergency",
  "urgent",
  "life-threatening",
  "severe reaction",
  "swelling of throat",
  "swelling of face",
  "trouble breathing",
  "cannot breathe",
  "stop breathing",
  "unconscious",
  "coma",
  "hemorrhage",
  "severe bleeding",
  "cardiac arrest",
];

export function isEmergencyQuery(query: string): boolean {
  const lower = query.toLowerCase();
  return EMERGENCY_KEYWORDS.some((keyword) => lower.includes(keyword));
}

export function getEmergencyMessage(): string {
  return (
    "⚠️ EMERGENCY: This may require urgent medical attention. " +
    "Contact local emergency services or go to the nearest emergency department immediately. " +
    "In India, call 112 for emergency services. " +
    "Do not wait for an online response."
  );
}

// ─── Dosage Safety Boundaries ─────────────────────────────────────────────

/**
 * Check if a dose description contains obviously dangerous patterns.
 * This is a basic safety check, NOT medical advice.
 */
export function hasUnsafeDosagePattern(doseText: string): boolean {
  const lower = doseText.toLowerCase();

  // Extremely large numbers that likely indicate user error
  const largeNumberMatch = lower.match(/(\d+)\s*(mg|ml|g|mcg|iu)/);
  if (largeNumberMatch) {
    const num = parseInt(largeNumberMatch[1]);
    if (num > 10000) return true; // 10g+ is suspicious for most oral medicines
  }

  // Patterns suggesting very frequent dosing
  const dangerousFrequency = [
    "every minute",
    "every second",
    "continuous",
    "non-stop",
    "unlimited",
  ];
  if (dangerousFrequency.some((p) => lower.includes(p))) return true;

  return false;
}

// ─── Formulation Distinction ──────────────────────────────────────────────

/**
 * Check if two formulations are compatible for comparison.
 * Different forms, routes, or release types are NOT automatically equivalent.
 */
export function areFormulationsCompatible(
  form1: string | null,
  route1: string | null,
  form2: string | null,
  route2: string | null
): boolean {
  // Different routes are not compatible
  if (route1 && route2 && route1.toLowerCase() !== route2.toLowerCase()) {
    return false;
  }

  // Different forms may not be compatible (tablet vs injection)
  if (form1 && form2) {
    const f1 = form1.toLowerCase();
    const f2 = form2.toLowerCase();
    if (f1 !== f2) {
      // Oral forms are generally comparable
      const oralForms = ["tablet", "capsule", "liquid", "syrup", "solution"];
      const isOral1 = oralForms.some((f) => f1.includes(f));
      const isOral2 = oralForms.some((f) => f2.includes(f));
      if (isOral1 && isOral2) return true;
      return false;
    }
  }

  return true;
}

// ─── Coverage Warnings ────────────────────────────────────────────────────

/**
 * Generate coverage warnings based on what data is available.
 */
export function getCoverageWarnings(
  hasDailyMedLabel: boolean,
  hasOpenFDALabel: boolean,
  hasRxNormIdentity: boolean,
  isIndianBrand: boolean,
  hasVerifiedIngredient: boolean
): string[] {
  const warnings: string[] = [];

  if (!hasRxNormIdentity) {
    warnings.push("Exact RxNorm identity could not be confirmed.");
  }

  if (!hasDailyMedLabel && !hasOpenFDALabel) {
    warnings.push("Official label information from DailyMed and openFDA is not available for this medicine.");
  }

  if (isIndianBrand && !hasVerifiedIngredient) {
    warnings.push(SAFETY_DISCLAIMERS.UNVERIFIED_INGREDIENT);
  }

  if (warnings.length === 0 && (!hasDailyMedLabel || !hasOpenFDALabel)) {
    warnings.push("Only partial label information was available from the supported sources.");
  }

  return warnings;
}
